In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('bias_scores.csv')

# find and print values for Asociated Press url
# print(df[df['domain'] == 'apnews.com'])

# drop [budak_score, fb_score, mturk_score]
# df = df.drop(columns=['budak_score', 'fb_score', 'mturk_score'])

# drop null values
# df = df.dropna()

print(f"Number of rows: {df.shape[0]}")

# print summary statistics
df.describe()

Number of rows: 19022

,score,rounded_n_shares,rounded_n_accts,fb_score,mturk_score,budak_score,allsides_score,allsides_score_community,pew_score
count,19022.000000,1.902200e+04,19022.000000,436.000000,384.000000,16.000000,195.000000,195.000000,34.000000
mean,-0.054210,5.584108e+03,708.731995,0.021890,-0.040799,-0.004495,-0.064103,0.041026,-0.062676
std,0.420337,2.067943e+05,7917.449312,0.619068,0.253277,0.085361,0.637928,0.540484,0.182270
min,-1.000000,5.000000e+01,50.000000,-0.998400,-0.916667,-0.224690,-1.000000,-1.000000,-0.320000
25%,-0.351075,1.000000e+02,100.000000,-0.448525,-0.083333,-0.024730,-0.500000,-0.500000,-0.184750
50%,-0.021700,2.000000e+02,100.000000,-0.090550,0.000000,-0.010580,0.000000,0.000000,-0.082000
75%,0.219700,6.000000e+02,200.000000,0.699625,0.000000,0.001937,0.500000,0.500000,-0.031000
max,0.983800,1.804750e+07,626200.000000,1.029500,1.000000,0.177770,1.000000,1.000000,0.416000

In [4]:
# get just the bias scores for New York Times, Breitbart, CNN, Business Insider, the Atlantic, Fox News, Talking Points Memo, Buzzfeed News, National Review, New York Post, the Guardian, NPR, Reuters, Vox, and the Washington Post
df = df[df['domain'].isin(['nytimes.com', 'breitbart.com', 'cnn.com', 'businessinsider.com', 'theatlantic.com', 'foxnews.com', 'talkingpointsmemo.com', 'buzzfeednews.com', 'nationalreview.com', 'nypost.com', 'theguardian.com', 'npr.org', 'reuters.com', 'vox.com', 'washingtonpost.com'])]

# sort by score
df = df.sort_values(by=['score'])

df

,domain,score,rounded_n_shares,rounded_n_accts,fb_score,mturk_score,budak_score,allsides_score,allsides_score_community,pew_score
259,talkingpointsmemo.com,-0.6732,14000,6200,-0.8614,-0.416667,NaN,NaN,NaN,NaN
72,vox.com,-0.5546,78700,24800,-0.6591,-0.416667,NaN,-0.5,-0.5,NaN
19,npr.org,-0.4161,216700,65400,-0.6103,-0.166667,NaN,0.0,-0.5,-0.320
57,theatlantic.com,-0.4148,91800,32100,-0.5424,-0.416667,NaN,-0.5,0.0,NaN
33,theguardian.com,-0.3893,153100,48000,-0.5723,-0.416667,NaN,-0.5,-0.5,-0.086
5,nytimes.com,-0.2602,1277000,149800,-0.5469,0.000000,-0.050888,-0.5,-0.5,-0.292
7,washingtonpost.com,-0.2342,602500,126300,-0.2568,-0.583333,-0.012491,-0.5,-0.5,-0.196
55,reuters.com,-0.1287,105400,32400,-0.0945,-0.250000,-0.008669,0.0,0.0,NaN
10,cnn.com,-0.1183,375700,98300,-0.2705,-0.666667,-0.023874,0.0,-0.5,-0.222
34,businessinsider.com,-0.0373,137800,47000,-0.0585,0.000000,NaN,0.0,0.0,NaN
69,nypost.com,0.1813,73600,26900,0.2497,-0.333333,NaN,1.0,0.5,NaN
47,foxnews.com,0.6079,148600,38300,0.7754,0.250000,0.131992,0.5,1.0,0.416
293,nationalreview.com,0.6361,11400,5300,0.9009,0.416667,NaN,1.0,1.0,NaN
238,breitbart.com,0.7419,34500,6800,0.9136,0.833333,0.177770,1.0,1.0,0.116

In [3]:
df

,domain,score,rounded_n_shares,rounded_n_accts,allsides_score,allsides_score_community,pew_score
5,nytimes.com,-0.2602,1277000,149800,-0.5,-0.5,-0.292
7,washingtonpost.com,-0.2342,602500,126300,-0.5,-0.5,-0.196
9,huffingtonpost.com,-0.2383,571800,121400,-1.0,-0.5,-0.154
10,cnn.com,-0.1183,375700,98300,0.0,-0.5,-0.222
14,buzzfeed.com,-0.1616,274600,79800,-0.5,-0.5,-0.028
19,npr.org,-0.4161,216700,65400,0.0,-0.5,-0.320
23,usatoday.com,0.0582,167000,61800,0.0,0.0,-0.078
33,theguardian.com,-0.3893,153100,48000,-0.5,-0.5,-0.086
36,nbcnews.com,-0.1558,118300,45800,-0.5,-0.5,-0.212
37,bloomberg.com,-0.0792,158700,45400,0.0,0.0,-0.054
39,politico.com,-0.1914,162700,43900,-0.5,0.0,-0.070
47,foxnews.com,0.6079,148600,38300,0.5,1.0,0.416
81,thinkprogress.org,-0.7193,63800,22400,-1.0,-0.5,-0.040
83,economist.com,-0.2302,59100,21100,-0.5,0.5,-0.116
101,bbc.com,-0.2578,36500,16400,0.0,-0.5,-0.274
114,abcnews.go.com,-0.0384,22900,14600,-0.5,0.0,-0.174
115,motherjones.com,-0.6966,33500,14600,-1.0,-0.5,-0.106
133,dailykos.com,-0.7052,54700,12900,-1.0,-0.5,-0.042
229,msnbc.com,-0.6243,15600,7100,-1.0,0.0,-0.224
235,theblaze.com,0.7889,30400,6900,1.0,0.5,0.170
238,breitbart.com,0.7419,34500,6800,1.0,1.0,0.116
7648,drudgereport.com,0.8839,200,100,1.0,1.0,0.158